name: Ionos Cloud Sonar OpenApi Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setting up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Cache maven dependencies
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-maven-repository
        with:
          path: |
            ~/.m2/repository
            ~/.gradle
            !~/.gradle/caches/*/plugin-resolution/
            !~/.m2/repository/org/openapitools/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: Run maven
        run: mvn --no-snapshot-updates --batch-mode --quiet install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=error

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "sonar-openapi-plugin/target/sonar-openapi-plugin.jar"
          name: "${{ env.RELEASE_VERSION }} (Ionos Cloud Sonar OpenApi Release)"
          token: ${{ secrets.GITHUB_TOKEN }}
